fix sqitch issue
it can't find sqitch.plan for some reason.
it was not in the correct directory, but in next higher up
(parent) directory.

null_resource.chef_server_config (remote-exec):       Error executing action `run` on resource 'execute[sqitch_deploy_/opt/opscode/embedded/service/bookshelf/schema]'
null_resource.chef_server_config (remote-exec):       ================================================================================

null_resource.chef_server_config (remote-exec):       Mixlib::ShellOut::ShellCommandFailed
null_resource.chef_server_config (remote-exec):       ------------------------------------
null_resource.chef_server_config (remote-exec):       Expected process to exit with [0, 1], but received '2'
null_resource.chef_server_config (remote-exec):       ---- Begin output of sqitch --engine pg --db-name bookshelf --db-host 127.0.0.1 --db-port 5432 --db-user chef_pgsql --top-dir /opt/opscode/embedded/service/bookshelf/schema deploy --verify ----
null_resource.chef_server_config (remote-exec):       STDOUT:
null_resource.chef_server_config (remote-exec):       STDERR: Possible precedence issue with control flow operator at /opt/opscode/embedded/lib/perl5/site_perl/5.34.0/App/Sqitch/Plan.pm line 578.
null_resource.chef_server_config (remote-exec):       Plan file /opt/opscode/embedded/service/bookshelf/schema/sqitch.plan does not exist
null_resource.chef_server_config (remote-exec):       ---- End output of sqitch --engine pg --db-name bookshelf --db-host 127.0.0.1 --db-port 5432 --db-user chef_pgsql --top-dir /opt/opscode/embedded/service/bookshelf/schema deploy --verify ----
null_resource.chef_server_config (remote-exec):       Ran sqitch --engine pg --db-name bookshelf --db-host 127.0.0.1 --db-port 5432 --db-user chef_pgsql --top-dir /opt/opscode/embedded/service/bookshelf/schema deploy --verify returned 2

null_resource.chef_server_config (remote-exec):       Resource Declaration:
null_resource.chef_server_config (remote-exec):       ---------------------
null_resource.chef_server_config (remote-exec):       # In /var/opt/opscode/local-mode-cache/cookbooks/infra-server/resources/pg_sqitch.rb

null_resource.chef_server_config (remote-exec):        30:     execute "sqitch_deploy_#{new_resource.name}" do
null_resource.chef_server_config (remote-exec):        31:       command <<-EOM.gsub(/\s+/, ' ').strip!
null_resource.chef_server_config (remote-exec):        32:         sqitch --engine pg
null_resource.chef_server_config (remote-exec):        33:                --db-name #{new_resource.database}
null_resource.chef_server_config (remote-exec):        34:                --db-host #{new_resource.hostname}
null_resource.chef_server_config (remote-exec):        35:                --db-port #{new_resource.port}
null_resource.chef_server_config (remote-exec):        36:                --db-user #{new_resource.username}
null_resource.chef_server_config (remote-exec):        37:                --top-dir #{new_resource.name}
null_resource.chef_server_config (remote-exec):        38:                deploy #{target} --verify
null_resource.chef_server_config (remote-exec):        39:       EOM
null_resource.chef_server_config (remote-exec):        40:       environment 'PERL5LIB' => "/opt/#{ChefUtils::Dist::Org::LEGACY_CONF_DIR}/embedded/lib", # force us to use omnibus perl
null_resource.chef_server_config (remote-exec):        41:                   'LD_LIBRARY_PATH' => "/opt/#{ChefUtils::Dist::Org::LEGACY_CONF_DIR}/embedded/lib", # force us to use omnibus libraries
null_resource.chef_server_config (remote-exec):        42:                   'PGPASSWORD' => new_resource.password,
null_resource.chef_server_config (remote-exec):        43:                   'PGSSLMODE' => new_resource.sslmode
null_resource.chef_server_config (remote-exec):        44:
null_resource.chef_server_config (remote-exec):        45:       # Sqitch Return Codes
null_resource.chef_server_config (remote-exec):        46:       # 0 - when changes are applied
null_resource.chef_server_config (remote-exec):        47:       # 1 - when everything is ok but no changes were made
null_resource.chef_server_config (remote-exec):        48:       # 2(+?) - when an error occurs.
null_resource.chef_server_config (remote-exec):        49:       returns [0, 1]
null_resource.chef_server_config (remote-exec):        50:     end
null_resource.chef_server_config (remote-exec):        51:   end

null_resource.chef_server_config (remote-exec):       Compiled Resource:
null_resource.chef_server_config (remote-exec):       ------------------
null_resource.chef_server_config (remote-exec):       # Declared in /var/opt/opscode/local-mode-cache/cookbooks/infra-server/resources/pg_sqitch.rb:30:in `block (2 levels) in class_from_file'

null_resource.chef_server_config (remote-exec):       execute("sqitch_deploy_/opt/opscode/embedded/service/bookshelf/schema") do
null_resource.chef_server_config (remote-exec):         action [:run]
null_resource.chef_server_config (remote-exec):         default_guard_interpreter :execute
null_resource.chef_server_config (remote-exec):         command "sqitch --engine pg --db-name bookshelf --db-host 127.0.0.1 --db-port 5432 --db-user chef_pgsql --top-dir /opt/opscode/embedded/service/bookshelf/schema deploy --verify"
null_resource.chef_server_config (remote-exec):         declared_type :execute
null_resource.chef_server_config (remote-exec):         cookbook_name "infra-server"
null_resource.chef_server_config (remote-exec):         domain nil
null_resource.chef_server_config (remote-exec):         user nil
null_resource.chef_server_config (remote-exec):         environment {"PERL5LIB"=>"/opt/opscode/embedded/lib", "LD_LIBRARY_PATH"=>"/opt/opscode/embedded/lib", "PGPASSWORD"=>"834924eba17f9438f22d787723737b303d7dc117e17e4aeb18a07642fae098a75c82e8b8c319e8568923108a59e80903a4ac", "PGSSLMODE"=>"disable"}
null_resource.chef_server_config (remote-exec):         returns [0, 1]
null_resource.chef_server_config (remote-exec):       end

null_resource.chef_server_config (remote-exec):       System Info:
null_resource.chef_server_config (remote-exec):       ------------
null_resource.chef_server_config (remote-exec):       chef_version=16.17.51
null_resource.chef_server_config (remote-exec):       platform=redhat
null_resource.chef_server_config (remote-exec):       platform_version=7.9
null_resource.chef_server_config (remote-exec):       ruby=ruby 2.7.5p203 (2021-11-24 revision f69aeb8314) [x86_64-linux]
null_resource.chef_server_config (remote-exec):       program_name=/opt/opscode/embedded/bin/chef-client
null_resource.chef_server_config (remote-exec):       executable=/opt/opscode/embedded/bin/chef-client

null_resource.chef_server_config (remote-exec):     ================================================================================
null_resource.chef_server_config (remote-exec):     Error executing action `deploy` on resource 'pg_sqitch[/opt/opscode/embedded/service/bookshelf/schema]'
null_resource.chef_server_config (remote-exec):     ================================================================================

null_resource.chef_server_config (remote-exec):     Mixlib::ShellOut::ShellCommandFailed
null_resource.chef_server_config (remote-exec):     ------------------------------------
null_resource.chef_server_config (remote-exec):     execute[sqitch_deploy_/opt/opscode/embedded/service/bookshelf/schema] (/var/opt/opscode/local-mode-cache/cookbooks/infra-server/resources/pg_sqitch.rb line 30) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0, 1], but received '2'
null_resource.chef_server_config (remote-exec):     ---- Begin output of sqitch --engine pg --db-name bookshelf --db-host 127.0.0.1 --db-port 5432 --db-user chef_pgsql --top-dir /opt/opscode/embedded/service/bookshelf/schema deploy --verify ----
null_resource.chef_server_config (remote-exec):     STDOUT:
null_resource.chef_server_config (remote-exec):     STDERR: Possible precedence issue with control flow operator at /opt/opscode/embedded/lib/perl5/site_perl/5.34.0/App/Sqitch/Plan.pm line 578.
null_resource.chef_server_config (remote-exec):     Plan file /opt/opscode/embedded/service/bookshelf/schema/sqitch.plan does not exist
null_resource.chef_server_config (remote-exec):     ---- End output of sqitch --engine pg --db-name bookshelf --db-host 127.0.0.1 --db-port 5432 --db-user chef_pgsql --top-dir /opt/opscode/embedded/service/bookshelf/schema deploy --verify ----
null_resource.chef_server_config (remote-exec):     Ran sqitch --engine pg --db-name bookshelf --db-host 127.0.0.1 --db-port 5432 --db-user chef_pgsql --top-dir /opt/opscode/embedded/service/bookshelf/schema deploy --verify returned 2

null_resource.chef_server_config (remote-exec):     Resource Declaration:
null_resource.chef_server_config (remote-exec):     ---------------------
null_resource.chef_server_config (remote-exec):     # In /var/opt/opscode/local-mode-cache/cookbooks/infra-server/recipes/bookshelf_database.rb

null_resource.chef_server_config (remote-exec):      71: pg_sqitch "/opt/#{ChefUtils::Dist::Org::LEGACY_CONF_DIR}/embedded/service/bookshelf/schema" do
null_resource.chef_server_config (remote-exec):      72:   hostname postgres_attrs['vip']
null_resource.chef_server_config (remote-exec):      73:   port     postgres_attrs['port']
null_resource.chef_server_config (remote-exec):      74:   username postgres_attrs['db_connection_superuser'] || postgres_attrs['db_superuser']
null_resource.chef_server_config (remote-exec):      75:   password PrivateChef.credentials.get('postgresql', 'db_superuser_password')
null_resource.chef_server_config (remote-exec):      76:   database 'bookshelf'
null_resource.chef_server_config (remote-exec):      77:   sslmode postgres_attrs['sslmode']
null_resource.chef_server_config (remote-exec):      78:   action :nothing
null_resource.chef_server_config (remote-exec):      79: end

null_resource.chef_server_config (remote-exec):     Compiled Resource:
null_resource.chef_server_config (remote-exec):     ------------------
null_resource.chef_server_config (remote-exec):     # Declared in /var/opt/opscode/local-mode-cache/cookbooks/infra-server/recipes/bookshelf_database.rb:71:in `from_file'

null_resource.chef_server_config (remote-exec):     pg_sqitch("/opt/opscode/embedded/service/bookshelf/schema") do
null_resource.chef_server_config (remote-exec):       action [:nothing]
null_resource.chef_server_config (remote-exec):       default_guard_interpreter :default
null_resource.chef_server_config (remote-exec):       declared_type :pg_sqitch
null_resource.chef_server_config (remote-exec):       cookbook_name "infra-server"
null_resource.chef_server_config (remote-exec):       recipe_name "bookshelf_database"
null_resource.chef_server_config (remote-exec):       hostname "127.0.0.1"
null_resource.chef_server_config (remote-exec):       port 5432
null_resource.chef_server_config (remote-exec):       username "chef_pgsql"
null_resource.chef_server_config (remote-exec):       password "834924eba17f9438f22d787723737b303d7dc117e17e4aeb18a07642fae098a75c82e8b8c319e8568923108a59e80903a4ac"
null_resource.chef_server_config (remote-exec):       database "bookshelf"
null_resource.chef_server_config (remote-exec):       sslmode "disable"
null_resource.chef_server_config (remote-exec):     end

null_resource.chef_server_config (remote-exec):     System Info:
null_resource.chef_server_config (remote-exec):     ------------
null_resource.chef_server_config (remote-exec):     chef_version=16.17.51
null_resource.chef_server_config (remote-exec):     platform=redhat
null_resource.chef_server_config (remote-exec):     platform_version=7.9
null_resource.chef_server_config (remote-exec):     ruby=ruby 2.7.5p203 (2021-11-24 revision f69aeb8314) [x86_64-linux]
null_resource.chef_server_config (remote-exec):     program_name=/opt/opscode/embedded/bin/chef-client
null_resource.chef_server_config (remote-exec):     executable=/opt/opscode/embedded/bin/chef-client

null_resource.chef_server_config (remote-exec): Recipe: infra-server::haproxy
null_resource.chef_server_config (remote-exec):   * component_runit_service[haproxy] action restart
null_resource.chef_server_config (remote-exec):   Recipe: <Dynamically Defined Resource>
null_resource.chef_server_config (remote-exec):     * service[haproxy] action nothing (skipped due to action :nothing)
null_resource.chef_server_config (remote-exec):     * runit_service[haproxy] action restart
null_resource.chef_server_config (remote-exec):  (up to date)
null_resource.chef_server_config (remote-exec):      (up to date)

null_resource.chef_server_config (remote-exec): Running handlers:
null_resource.chef_server_config (remote-exec): Running handlers complete
null_resource.chef_server_config (remote-exec): Chef Infra Client failed. 68 resources updated in 56 seconds
null_resource.chef_server_config (remote-exec): [2022-05-05T22:12:45+00:00] FATAL: Stacktrace dumped to /var/opt/opscode/local-mode-cache/chef-stacktrace.out
null_resource.chef_server_config (remote-exec): [2022-05-05T22:12:45+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
null_resource.chef_server_config (remote-exec): [2022-05-05T22:12:45+00:00] FATAL: Mixlib::ShellOut::ShellCommandFailed: pg_sqitch[/opt/opscode/embedded/service/bookshelf/schema] (infra-server::bookshelf_database line 71) had an error: Mixlib::ShellOut::ShellCommandFailed: execute[sqitch_deploy_/opt/opscode/embedded/service/bookshelf/schema] (/var/opt/opscode/local-mode-cache/cookbooks/infra-server/resources/pg_sqitch.rb line 30) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0, 1], but received '2'
null_resource.chef_server_config (remote-exec): ---- Begin output of sqitch --engine pg --db-name bookshelf --db-host 127.0.0.1 --db-port 5432 --db-user chef_pgsql --top-dir /opt/opscode/embedded/service/bookshelf/schema deploy --verify ----
null_resource.chef_server_config (remote-exec): STDOUT:
null_resource.chef_server_config (remote-exec): STDERR: Possible precedence issue with control flow operator at /opt/opscode/embedded/lib/perl5/site_perl/5.34.0/App/Sqitch/Plan.pm line 578.
null_resource.chef_server_config (remote-exec): Plan file /opt/opscode/embedded/service/bookshelf/schema/sqitch.plan does not exist
null_resource.chef_server_config (remote-exec): ---- End output of sqitch --engine pg --db-name bookshelf --db-host 127.0.0.1 --db-port 5432 --db-user chef_pgsql --top-dir /opt/opscode/embedded/service/bookshelf/schema deploy --verify ----
null_resource.chef_server_config (remote-exec): Ran sqitch --engine pg --db-name bookshelf --db-host 127.0.0.1 --db-port 5432 --db-user chef_pgsql --top-dir /opt/opscode/embedded/service/bookshelf/schema deploy --verify returned 2
null_resource.chef_server_config (remote-exec): Traceback (most recent call last):
null_resource.chef_server_config (remote-exec): 	4: from /bin/chef-server-ctl:185:in `<main>'
null_resource.chef_server_config (remote-exec): 	3: from /bin/chef-server-ctl:185:in `load'
null_resource.chef_server_config (remote-exec): 	2: from /opt/opscode/embedded/lib/ruby/gems/2.7.0/gems/chef-server-ctl-1.1.0/bin/chef-server-ctl:356:in `<top (required)>'
null_resource.chef_server_config (remote-exec): 	1: from /opt/opscode/embedded/lib/ruby/gems/2.7.0/gems/omnibus-ctl-0.6.10/lib/omnibus-ctl.rb:748:in `run'
null_resource.chef_server_config (remote-exec): /opt/opscode/embedded/lib/ruby/gems/2.7.0/gems/chef-server-ctl-1.1.0/bin/chef-server-ctl:310:in `reconfigure': undefined method `[]' for nil:NilClass (NoMethodError)

Signed-off-by: Lincoln Baker <lbaker@chef.io>