Add test for knife-opc org creation
There was a breakage here by changes to chef/chef.
Creating an org with a user in it raises the following:
```
Exception: NoMethodError: undefined method `get_rest' for #<Chef::ServerAPI:0x00000002347a18>`
```

The test will pass when https://github.com/chef/chef/pull/4432 is merged