Upgrade Erlang to 24.2.
- Upgrade to Erlang 24.3.2
- Install/build with correct version of Erlang
- Fix deprecations, incompatibilities, etc.

Note: rebar3 could not be upgraded as of yet, because it causes various
failures.  An issue has been created for it.

Below are a few of the many issues addressed while doing this work:

- Jiffy update for Erlang 24+ (erl_interface compilation errors)

ld: library not found for -lerl_interface
clang: error: linker command failed with exit code 1 (use -v to see invocation)
sh(c++ c_src/decoder.o c_src/encoder.o c_src/jiffy.o c_src/utf8.o c_src/util.o c_src/doubles.o c_src/objects.o c_src/double-conversion/bignum-dtoa.o c_src/double-conversion/bignum.o c_src/double-conversion/cached-powers.o c_src/double-conversion/diy-fp.o c_src/double-conversion/double-conversion.o c_src/double-conversion/fast-dtoa.o c_src/double-conversion/fixed-dtoa.o c_src/double-conversion/strtod.o  -lstdc++ -bundle -flat_namespace -undefined suppress  -L"/usr/local/Cellar/erlang@24/24.3.4.1/lib/erlang/lib/erl_interface-5.2.2/lib" -lerl_interface -lei -o priv/jiffy.so)
failed with return code 1 and the following output:
ld: library not found for -lerl_interface
clang: error: linker command failed with exit code 1 (use -v to see invocation)

===> Hook for compile failed!

- Fix bcrypt

- Fix depsolver jiffy issues

- Fix LDAP failures after Erlang changes to #eldap_search_result record.

An additional field was added by Erlang to the #eldap_search_result
record to support paged search results.  This caused a bad match, which
was difficult to find because the bad match exception was being caught.

https://github.com/erlang/otp/pull/5538

- Fix unused type failure.

encountered the following minor compilation error below, but if the type is
removed, we get an error that the type is needed.  the best way is to
not spend hours on this, and just add the compilation flag (that's why
it's there) and move on.

===> Compiling bookshelf
===> Compiling src/bksw_sql.erl failed
src/bksw_sql.erl:22:2: type dict() is unused

- Fix verify pipeline errors in oc_bifrost.

the way jiffy throws errors was changed, due to erlang changes.

- Fix http_uri:encode/decode deprecations.

===> Compiling src/bksw_io_names.erl failed
src/bksw_io_names.erl:34:5: http_uri:encode/1 is deprecated and will be removed in OTP 25; use uri_string functions instead
src/bksw_io_names.erl:39:5: http_uri:decode/1 is deprecated and will be removed in OTP 25; use uri_string functions instead

- Fix bookshelf verify pipeline errors.

https://buildkite.com/chef-oss/chef-chef-server-main-verify/builds/468#0181ffdf-75e7-4942-9bae-7c02fde88a4a

Signed-off-by: Lincoln Baker <lbaker@chef.io>