Update to Erlang 25.2.5.2
Update to Erlang 26.2.5.2

Update plan.sh files to erlang26

Upgrade rebar3

Recompile Elvis and fix elvis complaints

Remove eper

    It's old and unmaintained, and now it won't compile without warnings.
    the last commit was 6-10 years ago.

    Most of the tools within it now have more updated equivalents
    elsewhere.

    Choices:

    1) just remove it
    2) fork it, fix compile errors, maintain it
    3) remove it, then when and where needed, use updated equivalents.

    For now, going with #1.

Fix compilation errors in depsolver

Fix undefined type error and syntax error.

Fix dialyzer errors

pg2 -> pg
    pg2 was removed by Erlang.

start -> ensure_started

Add {minor_version, 1} option to term_to_binary pursuant to Erlang 26 update.

    term_to_binary changed.  This option is now needed in order to maintain
    current behavior and avoid failures.

Add [{minor_version, 1}] option to all term_to_binary function calls

    It's probably not good to have some calls using this option and other
    calls not using it.

Fix /_stats API pedant test failure following update to erlang 26x

  2) /_stats API endpoint returns prometheus output ?format=text
     Failure/Error: expect(names.uniq).to match_array(PROMETHEUS_RESPONSE_TYPE_MAP.keys)

       expected collection contained:  ["chef_index_batch_completed_latency_ms_bucket", "chef_index_batch_completed_latency_ms_count", "chef... "pg_stat_tidx_blks_read", "pg_stat_toast_blks_hit", "pg_stat_toast_blks_read", "pg_stat_tup_fetch"]
       actual collection contained:    ["chef_index_batch_completed_latency_ms_bucket", "chef_index_batch_completed_latency_ms_count", "chef... "pg_stat_tidx_blks_read", "pg_stat_toast_blks_hit", "pg_stat_toast_blks_read", "pg_stat_tup_fetch"]
       the missing elements were:      ["erlang_mnesia_committed_transactions", "erlang_mnesia_failed_transactions", "erlang_mnesia_held_loc...d_transactions", "erlang_mnesia_transaction_coordinators", "erlang_mnesia_transaction_participants"]
     # ./spec/api/stats_spec.rb:218:in `block (2 levels) in <top (required)>'

Add ssl option verify_none following update to Erlang 26.

    Erlang changed this from a default option to an option which now has to
    be specified.  Not specifying it was causing failures in SSL when using
    a self-signed cert (see below).

    1) Server-side reindexing reindexing OPC it should behave like Reindexing works for all object types
       Failure/Error: identifiers.should_not include(name)
         expected ["pedant_node_test"] not to include "pedant_node_test"
       Shared Example Group: "Reindexing" called from ./spec/api/reindex_spec.rb:20
       # ./lib/pedant/rspec/search_util.rb:932:in `block in do_search'
       # ./lib/pedant/rspec/search_util.rb:769:in `with_search_polling'
       # ./lib/pedant/rspec/search_util.rb:919:in `do_search'
       # ./lib/pedant/rspec/search_util.rb:888:in `should_not_find'
       # ./lib/pedant/rspec/search_util.rb:950:in `block (2 levels) in <module:RSpec>'

Signed-off-by: Lincoln Baker <lbaker@chef.io>