fix cookstyle failure
Error: resources/pg_upgrade.rb:117:5: C: [Correctable] Style/ReturnNil:
Use return instead of return nil.
    return nil if dir.nil?

Signed-off-by: Lincoln Baker <lbaker@chef.io>