fix: adding missing whitespaces in queries
There are missing whitespaces in some of the queries which
make triggers errors when running against a PostgreSQL 17 database.
Apparently due to a more stringent SQL parsing in that version.

The following error in the DB logs was corrected by the changes at the
time of associating a user to an organization:

```console
ERROR: trailing junk after parameter at or near "$3WHERE" at character 62
STATEMENT: UPDATE groups SET last_updated_by= $1, updated_at= $2, name= $3WHERE| id=
```

Signed-off-by: Mauro Oddi <mauro.oddi@progress.com>