wip try again to fix license scout error [DIDN'T WORK]
pointed to an older erlcloud sha. didn't work; error pasted below from verify
pipeline:

INFO: [reporter] Allowed licenses: Apache-1.0, Apache-1.1, Apache-2.0, Artistic-2.0, BSD-1-Clause, BSD-2-Clause, BSD-3-Clause, BSD-3-Clause-Attribution, BSD-Source-Code, BSL-2.0, bzip2-1.0.6, CC0-1.0, CC-BY-2.0, CC-BY-3.0, CC-BY-4.0, curl, gnuplot, ICU, ISC, MIT, MPL-2.0, OpenSSL, PHP-3.0, PHP-3.01, PostgreSQL, Python-2.0, Ruby, SAX-PD, Unlicense, WTFPL, Zlib
+--------+-----------------------------------------------------+------------+--------------+
| Type   | Dependency                                          | License(s) | Results      |
+--------+-----------------------------------------------------+------------+--------------+
| erlang | erlcloud (82b2c303077a343b0420b9550d71d25d923bf833) |            | Undetermined |
|        | lhttpc (1.6.2)                                      |            | Missing      |
+--------+-----------------------------------------------------+------------+--------------+

Additional steps are required in order to pass Open Source license compliance:
  * Please add fallback licenses for the 'Missing' or 'Undetermined' dependencies
         https://github.com/chef/license_scout#fallback-licenses
Error: The command exited with status 1

Signed-off-by: Lincoln Baker <lbaker@chef.io>